name: CI

on: [pull_request]

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install ruby version specified in .ruby-version
        uses: ruby/setup-ruby@v1
      - name: Check contributors
        run: |
          ./script/check_contributors_md.rb
